CREATE DATABASE IF NOT EXISTS neutron;
GRANT ALL PRIVILEGES ON neutron.* TO '%NEUTRON_DB_USER%'@'localhost' \
    IDENTIFIED BY '%NEUTRON_DB_PASS%';
GRANT ALL PRIVILEGES ON neutron.* TO '%NEUTRON_DB_USER%'@'%' \
    IDENTIFIED BY '%NEUTRON_DB_PASS%';
