CREATE DATABASE IF NOT EXISTS nova;
GRANT ALL PRIVILEGES ON nova.* TO '%NOVA_DB_USER%'@'localhost' \
    IDENTIFIED BY '%NOVA_DB_PASS%';
GRANT ALL PRIVILEGES ON nova.* TO '%NOVA_DB_USER%'@'%' \
    IDENTIFIED BY '%NOVA_DB_PASS%';
