CREATE DATABASE IF NOT EXISTS glance;
GRANT ALL PRIVILEGES ON glance.* TO '%GLANCE_DB_USER%'@'localhost' \
    IDENTIFIED BY '%GLANCE_DB_PASS%';
GRANT ALL PRIVILEGES ON glance.* TO '%GLANCE_DB_USER%'@'%' \
    IDENTIFIED BY '%GLANCE_DB_PASS%';
